INSERT INTO team(name) VALUES ('Anaheim Ducks');
INSERT INTO team(name) VALUES ('Arizona Coyotes');
INSERT INTO team(name) VALUES ('Calgary Flames');
INSERT INTO team(name) VALUES ('Edmonton Oilers');
INSERT INTO team(name) VALUES ('Los Angeles Kings');
INSERT INTO team(name) VALUES ('San Jose Sharks');
INSERT INTO team(name) VALUES ('Vancouver Canucks');
INSERT INTO team(name) VALUES ('Chicago Blackhawks');
INSERT INTO team(name) VALUES ('Colorado Avalanche');
INSERT INTO team(name) VALUES ('Dallas Stars');
INSERT INTO team(name) VALUES ('Minnesota Wild');
INSERT INTO team(name) VALUES ('Nashville Predators');
INSERT INTO team(name) VALUES ('St Louis Blues');
INSERT INTO team(name) VALUES ('Winnipeg Jets');
INSERT INTO team(name) VALUES ('Boston Bruins');
INSERT INTO team(name) VALUES ('Buffalo Sabres');
INSERT INTO team(name) VALUES ('Detroit Red Wings');
INSERT INTO team(name) VALUES ('Florida Panthers');
INSERT INTO team(name) VALUES ('Montreal Canadiens');
INSERT INTO team(name) VALUES ('Ottawa Senators');
INSERT INTO team(name) VALUES ('Tampa Bay Lightning');
INSERT INTO team(name) VALUES ('Toronto Maple Leafs');
INSERT INTO team(name) VALUES ('Columbus Blue Jackets');
INSERT INTO team(name) VALUES ('New Jersey Devils');
INSERT INTO team(name) VALUES ('New York Islanders');
INSERT INTO team(name) VALUES ('New York Rangers');
INSERT INTO team(name) VALUES ('Philadelphia Flyers');
INSERT INTO team(name) VALUES ('Pittsburgh Penguins');
INSERT INTO team(name) VALUES ('Washington Capitals');
INSERT INTO team(name) VALUES ('Carolina Hurricanes');